// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0YxjXeruc3xHtvcmo_TvUMSlXu2NTUhI',
    appId: '1:906402032628:web:ca6ee0308a3f253a11e7a1',
    messagingSenderId: '906402032628',
    projectId: 'movie-17680',
    authDomain: 'movie-17680.firebaseapp.com',
    storageBucket: 'movie-17680.appspot.com',
    measurementId: 'G-VV6MSG1ED4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJHQXoqMqFlOTnW3OfobeFWtT5qetJwQ',
    appId: '1:906402032628:android:01947e6c99f6d73811e7a1',
    messagingSenderId: '906402032628',
    projectId: 'movie-17680',
    storageBucket: 'movie-17680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNq8BsRPV_7Y9GmgI7tsZc-fpdjmbsUk',
    appId: '1:906402032628:ios:2d7f8abfaa34b02e11e7a1',
    messagingSenderId: '906402032628',
    projectId: 'movie-17680',
    storageBucket: 'movie-17680.appspot.com',
    iosBundleId: 'com.example.cinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNq8BsRPV_7Y9GmgI7tsZc-fpdjmbsUk',
    appId: '1:906402032628:ios:730949c5b415965f11e7a1',
    messagingSenderId: '906402032628',
    projectId: 'movie-17680',
    storageBucket: 'movie-17680.appspot.com',
    iosBundleId: 'com.example.cinema.RunnerTests',
  );
}
